<?php /** @var Magento\Framework\View\TemplateEngine\Php $this */ ?>

<div>
    <div style="
        background-color: <?php echo $this->getData('background_color') ?>;
        border: #000000 2px dashed;
        border-radius: 30px;
        text-align: center;
    ">
        <h2>
            <?php echo __('Custom snippet block. %1', $this->getData('snippet_message')) ?>
        </h2>
    </div>
</div>
